# -*- coding: utf-8 -*-
"""us-accidents-analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pNaKRyY6y85t2m7WyQ1Cj7_IRdV5uxob
"""

# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('us-accidents-analysis')
jovian.set_colab_id('1pNaKRyY6y85t2m7WyQ1Cj7_IRdV5uxob')

"""# us-accidents-analysis

Use the "Run" button to execute the code.
"""

!pip install jovian --upgrade --quiet

import jovian

# Execute this to save new versions of the notebook
jovian.commit(project="us-accidents-analysis")

"""# US Accidents Exploratory Data Analysis

Talk about dataset (source, what it contains, how it will be useful)
  - Kaggle 
  - Information about accidents
  - Can be useful to prevent accidents
  
*This does not include or contain data about New York
"""

pip install opendatasets --upgrade --quiet

"""## Download the Data"""

import opendatasets as od

download_url = 'https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents'

od.download(download_url)

data_filename = './us-accidents/US_Accidents_Dec21_updated.csv'

"""⬆⬆⬆⬆⬆  This is how I downloaded the dataset to this platform. It is from Kaggle and it is titled, "US Accidents".

## Ask & Answer Questions

1. Are there more accidents in warmer or colder areas? 
2. Which 5 states has the highest number of accidents?
3. Does New York show up in the data? If so, why is the count lower if it is the most populated city? 
4. Looking at the top 100 cities with the highest number of accidents, which states do they belong to most frequently?
5. What time of the day are accidents most frequent?
6. Which days of the week have the most accidents?
7. Which months have the most accidents?
8. What is the trend of accidents year by year? (decreasing/increasing?)

## Data Preparation and Cleaning

- Here I will do a few things:

1.   Load the file using Pandas
2.   Look at some information about the data & the columns
3.   Fix any missing or incorrect values
"""

import pandas as pd

df = pd.read_csv(data_filename)

"""⬆ Here I have made the alias, 'df', to make my work easier as I go"""

df

"""⬆  As you can see this dataset is large and full of information! Let's dive in!"""

df.columns

df.info

df.describe()

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']

numeric_df = df.select_dtypes(include=numerics)
len(numeric_df.columns)

"""Percentage of missing values per column:

"""

missing_percentages = df.isna().sum().sort_values(ascending=False) / len(df)
missing_percentages

missing_percentages[missing_percentages != 0]

type(missing_percentages)

missing_percentages[missing_percentages != 0].plot(kind= 'barh')

"""I removed the columns that I don't want to use (null, insufficient data, no data)

## Exploratory Analysis and Visualization

Here are the columns we'll analyze:

1. City
2. Months
3. Start time
4. Start latitude, Start longitude
"""

df.columns

"""### Cities"""

cities = df.City.unique()
len(cities)

cities_by_accident = df.City.value_counts()
cities_by_accident

cities_by_accident[:20]

cities_by_accident[:100]

cities_by_accident[:20].plot(kind='barh')

"""⬆ Let's make this data a little easier to understand with a bar chart."""

import seaborn as sns
sns.set_style('darkgrid')

sns.histplot(cities_by_accident, log_scale=True)

cities_by_accident[cities_by_accident == 1]

high_accident_cities = cities_by_accident[cities_by_accident >= 1000]
low_accident_cities = cities_by_accident[cities_by_accident < 1000]

len(high_accident_cities) / len(cities)

sns.distplot(high_accident_cities)

sns.distplot(low_accident_cities)

"""### Start Time"""

df.Start_Time

df.Start_Time = pd.to_datetime(df.Start_Time)

df.Start_Time[0]

sns.distplot(df.Start_Time.dt.hour, bins=24, norm_hist=True)

"""- A high percentage of accidents occur between 6:00am-10:00am (probably people in a rush to work, and/or traffic is higher due to the cummute)
- Next highest percentage is 3:00pm-6:00pm

Is the distribution of accidents by hour the same on weekends as they are on weekdays? Let's look into it a bit more.

#### Day of the Week
"""

monday_start_time = df.Start_Time[df.Start_Time.dt.dayofweek == 0]
sns.distplot(monday_start_time.dt.hour, bins=24, kde=False, norm_hist=True)

sundays_start_time = df.Start_Time[df.Start_Time.dt.dayofweek == 6]
sns.distplot(sundays_start_time.dt.hour, bins=24, kde=False, norm_hist=True)

sns.distplot(df.Start_Time.dt.dayofweek, bins=7, kde=False, norm_hist=True)

"""So, there are definitely some differences here. On Sundays, the peak occurs between 10:00am and 3:00pm, unlike weekdays. This is porbably due to commutes, and a lot of people working the 9-5 type schedule. on weekends people tend to sleep in a little more which in turn could cause them to go out later on weekends.

## Months
"""

df_2019 = df[df.Start_Time.dt.year == 2019]
sns.distplot(df.Start_Time.dt.month, bins=12, kde=False, norm_hist=True)

df_2020 = df[df.Start_Time.dt.year == 2020]
sns.distplot(df.Start_Time.dt.month, bins=12, kde=False, norm_hist=True)

"""## Start Latitude & Longitude"""

df.Start_Lat

df.Start_Lng

sample_df = df.sample(int(0.1 * len(df)))

sns.scatterplot(x=df.Start_Lng, y=df.Start_Lat)

"""⬆⬆⬆⬆⬆ The dots on this geographic scatterplot are a bit too big and overwhelming, so I will make them smaller so we can get a better idea of the accidents across the US."""

sns.scatterplot(x=sample_df.Start_Lng, y=sample_df.Start_Lat, size=0.001)

"""⬆ This scatterplot shows a 10% sample. It is much more digestable and a lot less overwhelming with this scale. """

import folium

lat, lon = df.Start_Lat[0], df.Start_Lng[0]
lat, lon

for x in df[['Start_Lat', 'Start_Lng']].sample(100).iteritems():
  print(x[1])

from folium.plugins import HeatMap

zip(list(df.Start_Lat), list(df.Start_Lng))

sample_df = df.sample(int(0.1 * len(df)))
lat_lon_pairs = list(zip(list(sample_df.Start_Lat), list(sample_df.Start_Lng)))

f = folium.Figure(width=1000, height=500)

map_hooray = folium.Map(location = [38.27312, -98.5821872], zoom_start = 5)

map
HeatMap(lat_lon_pairs,size=0.001).add_to(map_hooray)
map_hooray

"""## Summary & Conclusion

Insights:
- No data for New York
- The number of accidents per city descreases exponentially
- Less than 5% of cities have more than 1000 accidents annually
- Over 1200 cities have just one accident
- There does not appear to be a significant difference between accidents in warmer or colder areas, but rather population density of cities and states.
- That being said, accidents have a higher rate in the winter months (as seen with December above, which has the highest accident rate of any month) most likely due to inclement weather such as ice, rain, snow, and overall slick road conditions. 
The volume of travel is also higher due to the holidays in the US around the winter months. Lastly, in winter the days are shorter, and nights are longer. It is dark outside earlier in the morning when people commute, and the sun is usually setting or set by the time they are finished with work. The darkness, as well as the weather can highly impact visibility while driving.
- The 3 states with cities where accidents occur the most are:
    1. Florida (Miami, Orlando, and Jacksonville)
    2. California (Los Angeles, Sacramento, and San Diego)
    3. Texas (Dallas, Houston, and Austin)
- As shown above, the time that accidents are most frequent tend to be during work commuting hours, 6:00am-10:00am, and 3:00pm-6:00pm.
- Friday is the day of the week that the most accidents occur.
- Overall, the number of accidents does show a slight decrease each year, which is great!

*It is important to note that there are some gaps and missing data in 2016, possibly 2017 as well; There seems to be an issue with the data pulled from Bing, some data was missing from this source.


"""